# Generated by Django 2.1.5 on 2019-02-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('FIR', 'Fire'), ('HAZ', 'Haze'), ('CAT', 'Cat on a tree'), ('TSU', 'Tsunami')], max_length=3)),
                ('incident_date', models.DateTimeField(verbose_name='date incident happens')),
                ('assistance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Assistance')),
            ],
        ),
    ]
