# Generated by Django 2.1.5 on 2019-03-03 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0004_auto_20190225_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='caller',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_closed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
