# Generated by Django 2.1.5 on 2019-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190303_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('FIR', 'Fire outbreak'), ('HAZ', 'Haze'), ('BIR', 'Bird flu outbreak'), ('TSU', 'Tsunami'), ('AFT', 'Earthquake Aftershock'), ('TER', 'Terrorist Activity')], max_length=3),
        ),
    ]
